---
# This file could be refactored to use Ansible roles
- hosts: couch
  tasks:
  - name: ensure required system packages are installed
    action: apt pkg={{item}} state=installed update-cache=yes
    sudo: yes
    with_items:
      - build-essential
      - python-setuptools
      - python-pip
      - python-apt
      - python-pycurl
      - python-software-properties

  # Setup couchdb    
  - name: get latest couchdb build
    apt_repository: repo='ppa:nilya/couchdb-1.3'

  - name: ensure couchdb is installed
    apt: pkg=couchdb state=latest update_cache=yes

  - name: ensure couchdb is running
    action: service name=couchdb state=started

  # Setup nginx for SSL termination
  # Required ENV vars
  #  export BUSBUD_SSL_CERTIFICATE=$(cat busbud.com.pem)
  #  export BUSBUD_SSL_CERTIFICATE_KEY=$(cat busbud.com.key)
  #  export BUSBUD_COUCHDB_AUTHUSER=...
  #  export BUSBUD_COUCHDB_AUTHPASSWORD=...
  - name: get latest nginx build
    apt_repository: repo='ppa:nginx/stable'

  - name: ensure nginx is installed
    apt: pkg=nginx state=latest update_cache=yes

  - name: setup SSL cert dir
    command: mkdir -p /home/busbud/certs

  - name: setup SSL cert
    copy: content="{{ lookup('env', 'BUSBUD_SSL_CERTIFICATE') }}" dest=/home/busbud/certs/busbud.com.pem

  - name: setup SSL cert key
    copy: content="{{ lookup('env', 'BUSBUD_SSL_CERTIFICATE_KEY') }}" dest=/home/busbud/certs/busbud.com.key

  - pip: name=passlib state=present
  - name: Add a user to a password file and ensure permissions are set
    htpasswd: path=/etc/nginx/htpasswd name="{{ lookup('env', 'BUSBUD_COUCHDB_AUTHUSER') }}" password="{{lookup('env', 'BUSBUD_COUCHDB_AUTHPASSWORD') }}" state=present owner=root group=www-data mode=0640

  - name: configure nginx as SSL terminator
    template: src=./roles/couchdb/templates/nginx.conf.j2 dest=/etc/nginx/sites-available/busbud

  - name: link to SSL termination config
    command: ln -v -s -f /etc/nginx/sites-available/busbud /etc/nginx/sites-enabled/busbud

  - name: ensure nginx is running
    action: service name=nginx state=started