---
- hosts: local
  tasks:
  - name: ensure git packages is installed
    action: apt pkg={{item}} state=installed update-cache=yes
    sudo: yes
    with_items:
      - git

  - name: pull the repo locally
    git: repo=git://github.com/cdnbacon/devops-taste-test.git
         dest=/home/devops-taste-test